author: [James Lemin]
institute: [an institute]
title: [Data Science]
tags:
  - "Data Science"
  - "Story telling"
  - nice
pdf-title: [Data Science and Visualisation]
author-meta: [James Lemin]
draft: false
date: [2024/06/30]
titlepage: true
toc-own-page: true
toc-title: [Contents]
toc-depth: [2]
lot: true #remove line to not include List of tables
lof: true #remove line to not include List of figures
bibliography: [references.bib]
biblio-title: [References]
